//
//  SongData.swift
//  Taylordle
//
//  Created by Agata Przykaza on 23/07/2024.
//

import Foundation

let songList: [SongModel] = [

    //TTPD
    SongModel(songTitle: "Fortnight", album: .TTPD, trackNumber: 1, trackLength: convertToSeconds(from: "03:48"), features: "Post Malone"),
        SongModel(songTitle: "The Tortured Poets Department", album: .TTPD, trackNumber: 2, trackLength: convertToSeconds(from: "04:53"), features: nil),
        SongModel(songTitle: "My Boy Only Breaks His Favorite Toys", album: .TTPD, trackNumber: 3, trackLength: convertToSeconds(from: "03:23"), features: nil),
        SongModel(songTitle: "Down Bad", album: .TTPD, trackNumber: 4, trackLength: convertToSeconds(from: "04:21"), features: nil),
        SongModel(songTitle: "So Long, London", album: .TTPD, trackNumber: 5, trackLength: convertToSeconds(from: "04:22"), features: nil),
        SongModel(songTitle: "But Daddy I Love HIm", album: .TTPD, trackNumber: 6, trackLength: convertToSeconds(from: "05:40"), features: nil),
        SongModel(songTitle: "Fresh Out the Slammer", album: .TTPD, trackNumber: 7, trackLength: convertToSeconds(from: "03:30"), features: nil),
        SongModel(songTitle: "Florida!!!", album:.TTPD, trackNumber: 8, trackLength: convertToSeconds(from: "03:35"), features: nil),
        SongModel(songTitle: "Guilty as Sin", album: .TTPD, trackNumber: 9, trackLength: convertToSeconds(from: "04:14"), features: nil),
        SongModel(songTitle: "Who's Afraid of Little Old Me?", album: .TTPD, trackNumber: 10, trackLength: convertToSeconds(from: "05:34"), features: nil),
        SongModel(songTitle: "I Can Fix Him (No Really I Can)", album: .TTPD, trackNumber: 11, trackLength: convertToSeconds(from: "02:36"), features: nil),
        SongModel(songTitle: "Loml", album: .TTPD, trackNumber: 12, trackLength: convertToSeconds(from: "04:37"), features: nil),
        SongModel(songTitle: "I Can Do It with a Broken Heart", album: .TTPD, trackNumber: 13, trackLength: convertToSeconds(from: "03:38"), features: nil),
        SongModel(songTitle: "The Smallest Man Who Ever Lived", album: .TTPD, trackNumber: 14, trackLength: convertToSeconds(from: "04:05"), features: nil),
        SongModel(songTitle: "The Alchemy", album: .TTPD, trackNumber: 15, trackLength: convertToSeconds(from: "03:16"), features: nil),
        SongModel(songTitle: "Clara Bow", album:.TTPD, trackNumber: 16, trackLength: convertToSeconds(from: "03:36"), features: nil),
        SongModel(songTitle: "The Black Dog", album: .TTPD, trackNumber: 17, trackLength: convertToSeconds(from: "03:58"), features: nil),
        SongModel(songTitle: "Imgonnagetyouback", album: .TTPD, trackNumber: 18, trackLength: convertToSeconds(from: "03:42"), features: nil),
        SongModel(songTitle: "The Albatross", album: .TTPD, trackNumber: 19, trackLength: convertToSeconds(from: "03:03"), features: nil),
        SongModel(songTitle: "Chole or Sam or Sophia or Marcus", album: .TTPD, trackNumber: 20, trackLength: convertToSeconds(from: "03:33"), features: nil),
        SongModel(songTitle: "How Did It End?", album: .TTPD, trackNumber: 21, trackLength: convertToSeconds(from: "03:58"), features: nil),
        SongModel(songTitle: "So High School", album: .TTPD, trackNumber: 22, trackLength: convertToSeconds(from: "03:48"), features: nil),
        SongModel(songTitle: "I Hate It Here", album: .TTPD, trackNumber: 23, trackLength: convertToSeconds(from: "04:03"), features: nil),
        SongModel(songTitle: "Thank You Aimee", album: .TTPD, trackNumber: 24, trackLength: convertToSeconds(from: "04:23"), features: nil),
        SongModel(songTitle: "I Look in People's Windows", album: .TTPD, trackNumber: 25, trackLength: convertToSeconds(from: "02:11"), features: nil),
        SongModel(songTitle: "The Prophecy", album: .TTPD, trackNumber: 26, trackLength: convertToSeconds(from: "04:09"), features: nil),
        SongModel(songTitle: "Cassandra", album: .TTPD, trackNumber: 27, trackLength: convertToSeconds(from: "04:00"), features: nil),
        SongModel(songTitle: "Peter", album: .TTPD, trackNumber: 28, trackLength: convertToSeconds(from: "04:43"), features: nil),
        SongModel(songTitle: "The Bolter", album: .TTPD, trackNumber: 29, trackLength: convertToSeconds(from: "03:58"), features: nil),
        SongModel(songTitle: "Robin", album: .TTPD, trackNumber: 30, trackLength: convertToSeconds(from: "04:00"), features: nil),
        SongModel(songTitle: "The Manuscript", album: .TTPD, trackNumber: 31, trackLength: convertToSeconds(from: "03:44"), features: nil),
    
    //MIDNIGHTS
    SongModel(songTitle: "Lavender Haze", album: .Midnights, trackNumber: 1, trackLength: convertToSeconds(from: "03:22"), features: nil),
        SongModel(songTitle: "Maroon", album: .Midnights, trackNumber: 2, trackLength: convertToSeconds(from: "03:38"), features: nil),
        SongModel(songTitle: "Anti-Hero", album: .Midnights, trackNumber: 3, trackLength: convertToSeconds(from: "03:20"), features: nil),
    SongModel(songTitle: "Snow on the Beach", album: .Midnights, trackNumber: 4, trackLength: convertToSeconds(from: "04:16"), features: "Lana Del Rey"),
        SongModel(songTitle: "You're on Your Own, Kid", album: .Midnights, trackNumber: 5, trackLength: convertToSeconds(from: "03:14"), features: nil),
        SongModel(songTitle: "Midnight Rain", album: .Midnights, trackNumber: 6, trackLength: convertToSeconds(from: "02:54"), features: nil),
        SongModel(songTitle: "Question...?", album: .Midnights, trackNumber: 7, trackLength: convertToSeconds(from: "03:30"), features: nil),
        SongModel(songTitle: "Vigilante Shit", album: .Midnights, trackNumber: 8, trackLength: convertToSeconds(from: "02:44"), features: nil),
        SongModel(songTitle: "Bejeweled", album: .Midnights, trackNumber: 9, trackLength: convertToSeconds(from: "03:14"), features: nil),
        SongModel(songTitle: "Labyrinth", album: .Midnights, trackNumber: 10, trackLength: convertToSeconds(from: "04:07"), features: nil),
        SongModel(songTitle: "Karma", album: .Midnights, trackNumber: 11, trackLength: convertToSeconds(from: "03:24"), features: nil),
        SongModel(songTitle: "Sweet Nothing", album: .Midnights, trackNumber: 12, trackLength: convertToSeconds(from: "03:08"), features: nil),
        SongModel(songTitle: "Mastermind", album: .Midnights, trackNumber: 13, trackLength: convertToSeconds(from: "03:11"), features: nil),
        SongModel(songTitle: "The Great War", album: .Midnights, trackNumber: 14, trackLength: convertToSeconds(from: "04:00"), features: nil),
        SongModel(songTitle: "Bigger Than the Whole Sky", album: .Midnights, trackNumber: 15, trackLength: convertToSeconds(from: "03:38"), features: nil),
        SongModel(songTitle: "Paris", album: .Midnights, trackNumber: 16, trackLength: convertToSeconds(from: "03:16"), features: nil),
        SongModel(songTitle: "High Infidelity", album: .Midnights, trackNumber: 17, trackLength: convertToSeconds(from: "03:51"), features: nil),
        SongModel(songTitle: "Glitch", album: .Midnights, trackNumber: 18, trackLength: convertToSeconds(from: "02:28"), features: nil),
        SongModel(songTitle: "Would've, Could've, Should've", album: .Midnights, trackNumber: 19, trackLength: convertToSeconds(from: "04:20"), features: nil),
        SongModel(songTitle: "Dear Reader", album: .Midnights, trackNumber: 20, trackLength: convertToSeconds(from: "03:45"), features: nil),
        SongModel(songTitle: "Hits Different", album: .Midnights, trackNumber: 21, trackLength: convertToSeconds(from: "03:54"), features: nil),
        SongModel(songTitle: "You're Losing Me", album: .Midnights, trackNumber: 22, trackLength: convertToSeconds(from: "04:38"), features: nil),
    
    //EVERMORE
    SongModel(songTitle: "willow", album: .evermore, trackNumber: 1, trackLength: convertToSeconds(from: "03:34"), features: nil),
        SongModel(songTitle: "champagne problems", album: .evermore, trackNumber: 2, trackLength: convertToSeconds(from: "04:04"), features: nil),
        SongModel(songTitle: "gold rush", album: .evermore, trackNumber: 3, trackLength: convertToSeconds(from: "03:05"), features: nil),
        SongModel(songTitle: "tis the damn season", album: .evermore, trackNumber: 4, trackLength: convertToSeconds(from: "03:49"), features: nil),
        SongModel(songTitle: "tolerate it", album: .evermore, trackNumber: 5, trackLength: convertToSeconds(from: "04:05"), features: nil),
        SongModel(songTitle: "no body, no crime", album: .evermore, trackNumber: 6, trackLength: convertToSeconds(from: "03:35"), features: "HAIM"),
        SongModel(songTitle: "happiness", album: .evermore, trackNumber: 7, trackLength: convertToSeconds(from: "05:15"), features: nil),
        SongModel(songTitle: "dorothea", album: .evermore, trackNumber: 8, trackLength: convertToSeconds(from: "03:45"), features: nil),
        SongModel(songTitle: "coney island", album: .evermore, trackNumber: 9, trackLength: convertToSeconds(from: "04:35"), features: "The National"),
        SongModel(songTitle: "ivy", album: .evermore, trackNumber: 10, trackLength: convertToSeconds(from: "04:20"), features: nil),
        SongModel(songTitle: "cowboy like me", album: .evermore, trackNumber: 11, trackLength: convertToSeconds(from: "04:35"), features: nil),
        SongModel(songTitle: "long story short", album: .evermore, trackNumber: 12, trackLength: convertToSeconds(from: "03:35"), features: nil),
        SongModel(songTitle: "marjorie", album: .evermore, trackNumber: 13, trackLength: convertToSeconds(from: "04:17"), features: nil),
        SongModel(songTitle: "closure", album: .evermore, trackNumber: 14, trackLength: convertToSeconds(from: "03:00"), features: nil),
        SongModel(songTitle: "evermore", album: .evermore, trackNumber: 15, trackLength: convertToSeconds(from: "05:04"), features: "Bon Iver"),
        SongModel(songTitle: "right where you left me", album: .evermore, trackNumber: 16, trackLength: convertToSeconds(from: "04:05"), features: nil),
        SongModel(songTitle: "it's time to go", album: .evermore, trackNumber: 17, trackLength: convertToSeconds(from: "04:15"), features: nil),
    
    //FOLKLORE
    SongModel(songTitle: "the 1", album: .folklore, trackNumber: 1, trackLength: convertToSeconds(from: "03:30"), features: nil),
        SongModel(songTitle: "cardigan", album: .folklore, trackNumber: 2, trackLength: convertToSeconds(from: "03:59"), features: nil),
        SongModel(songTitle: "the last great american dynasty", album: .folklore, trackNumber: 3, trackLength: convertToSeconds(from: "03:51"), features: nil),
        SongModel(songTitle: "exile", album: .folklore, trackNumber: 4, trackLength: convertToSeconds(from: "04:45"), features: "Bon Iver"),
        SongModel(songTitle: "my tears ricochet", album: .folklore, trackNumber: 5, trackLength: convertToSeconds(from: "04:15"), features: nil),
        SongModel(songTitle: "mirrorball", album: .folklore, trackNumber: 6, trackLength: convertToSeconds(from: "03:29"), features: nil),
        SongModel(songTitle: "seven", album: .folklore, trackNumber: 7, trackLength: convertToSeconds(from: "03:28"), features: nil),
        SongModel(songTitle: "august", album: .folklore, trackNumber: 8, trackLength: convertToSeconds(from: "04:21"), features: nil),
        SongModel(songTitle: "this is me trying", album: .folklore, trackNumber: 9, trackLength: convertToSeconds(from: "03:15"), features: nil),
        SongModel(songTitle: "illicit affairs", album: .folklore, trackNumber: 10, trackLength: convertToSeconds(from: "03:10"), features: nil),
        SongModel(songTitle: "invisible string", album: .folklore, trackNumber: 11, trackLength: convertToSeconds(from: "04:12"), features: nil),
        SongModel(songTitle: "mad woman", album: .folklore, trackNumber: 12, trackLength: convertToSeconds(from: "03:57"), features: nil),
        SongModel(songTitle: "epiphany", album: .folklore, trackNumber: 13, trackLength: convertToSeconds(from: "04:49"), features: nil),
        SongModel(songTitle: "betty", album: .folklore, trackNumber: 14, trackLength: convertToSeconds(from: "04:54"), features: nil),
        SongModel(songTitle: "peace", album: .folklore, trackNumber: 15, trackLength: convertToSeconds(from: "03:54"), features: nil),
        SongModel(songTitle: "hoax", album: .folklore, trackNumber: 16, trackLength: convertToSeconds(from: "03:40"), features: nil),
        SongModel(songTitle: "the lakes", album: .folklore, trackNumber: 17, trackLength: convertToSeconds(from: "03:31"), features: nil),
    
    //LOVER
    SongModel(songTitle: "I Forgot That You Existed", album: .Lover, trackNumber: 1, trackLength: convertToSeconds(from: "02:51"), features: nil),
        SongModel(songTitle: "Cruel Summer", album: .Lover, trackNumber: 2, trackLength: convertToSeconds(from: "02:58"), features: nil),
        SongModel(songTitle: "Lover", album: .Lover, trackNumber: 3, trackLength: convertToSeconds(from: "03:41"), features: nil),
        SongModel(songTitle: "The Man", album: .Lover, trackNumber: 4, trackLength: convertToSeconds(from: "03:10"), features: nil),
        SongModel(songTitle: "The Archer", album: .Lover, trackNumber: 5, trackLength: convertToSeconds(from: "03:31"), features: nil),
        SongModel(songTitle: "I Think He Knows", album: .Lover, trackNumber: 6, trackLength: convertToSeconds(from: "02:53"), features: nil),
        SongModel(songTitle: "Miss Americana & The Heartbreak Prince", album: .Lover, trackNumber: 7, trackLength: convertToSeconds(from: "03:54"), features: nil),
        SongModel(songTitle: "Paper Rings", album: .Lover, trackNumber: 8, trackLength: convertToSeconds(from: "03:42"), features: nil),
        SongModel(songTitle: "Cornelia Street", album: .Lover, trackNumber: 9, trackLength: convertToSeconds(from: "04:47"), features: nil),
        SongModel(songTitle: "Death By A Thousand Cuts", album: .Lover, trackNumber: 10, trackLength: convertToSeconds(from: "03:19"), features: nil),
        SongModel(songTitle: "London Boy", album: .Lover, trackNumber: 11, trackLength: convertToSeconds(from: "03:10"), features: nil),
    SongModel(songTitle: "Soon You'll Get Better", album: .Lover, trackNumber: 12, trackLength: convertToSeconds(from: "03:22"), features: "Dixie Chicks"),
       SongModel(songTitle: "False God", album: .Lover, trackNumber: 13, trackLength: convertToSeconds(from: "03:20"), features: nil),
       SongModel(songTitle: "You Need To Calm Down", album: .Lover, trackNumber: 14, trackLength: convertToSeconds(from: "02:51"), features: nil),
       SongModel(songTitle: "Afterglow", album: .Lover, trackNumber: 15, trackLength: convertToSeconds(from: "03:43"), features: nil),
       SongModel(songTitle: "ME!", album: .Lover, trackNumber: 16, trackLength: convertToSeconds(from: "03:13"), features: "Brendon Urie of Panic! At The Disco"),
       SongModel(songTitle: "It's Nice To Have A Friend", album: .Lover, trackNumber: 17, trackLength: convertToSeconds(from: "02:30"), features: nil),
       SongModel(songTitle: "Daylight", album: .Lover, trackNumber: 18, trackLength: convertToSeconds(from: "04:53"), features: nil),
       SongModel(songTitle: "All Of The Girls You Loved Before", album: .Lover, trackNumber: 19, trackLength: convertToSeconds(from: "03:41"), features: nil),
    //reputation
    SongModel(songTitle: "...Ready For It?", album: .reputation, trackNumber: 1, trackLength: convertToSeconds(from: "03:28"), features: nil),
       SongModel(songTitle: "End Game", album: .reputation, trackNumber: 2, trackLength: convertToSeconds(from: "04:04"), features: "Ed Sheeran & Future"),
       SongModel(songTitle: "I Did Something Bad", album: .reputation, trackNumber: 3, trackLength: convertToSeconds(from: "03:58"), features: nil),
       SongModel(songTitle: "Don't Blame Me", album: .reputation, trackNumber: 4, trackLength: convertToSeconds(from: "03:56"), features: nil),
       SongModel(songTitle: "Delicate", album: .reputation, trackNumber: 5, trackLength: convertToSeconds(from: "03:52"), features: nil),
       SongModel(songTitle: "Look What You Made Me Do", album: .reputation, trackNumber: 6, trackLength: convertToSeconds(from: "03:31"), features: nil),
       SongModel(songTitle: "So It Goes...", album: .reputation, trackNumber: 7, trackLength: convertToSeconds(from: "03:47"), features: nil),
       SongModel(songTitle: "Gorgeous", album: .reputation, trackNumber: 8, trackLength: convertToSeconds(from: "03:29"), features: nil),
       SongModel(songTitle: "Getaway Car", album: .reputation, trackNumber: 9, trackLength: convertToSeconds(from: "03:53"), features: nil),
       SongModel(songTitle: "King of My Heart", album: .reputation, trackNumber: 10, trackLength: convertToSeconds(from: "03:34"), features: nil),
       SongModel(songTitle: "Dancing With Our Hands Tied", album: .reputation, trackNumber: 11, trackLength: convertToSeconds(from: "03:31"), features: nil),
       SongModel(songTitle: "Dress", album: .reputation, trackNumber: 12, trackLength: convertToSeconds(from: "03:50"), features: nil),
       SongModel(songTitle: "This Is Why We Can't Have Nice Things", album: .reputation, trackNumber: 13, trackLength: convertToSeconds(from: "03:27"), features: nil),
       SongModel(songTitle: "Call It What You Want", album: .reputation, trackNumber: 14, trackLength: convertToSeconds(from: "03:23"), features: nil),
       SongModel(songTitle: "New Year's Day", album: .reputation, trackNumber: 15, trackLength: convertToSeconds(from: "03:55"), features: nil),
    
    //1989
    SongModel(songTitle: "Welcome To New York", album: .eightyNine, trackNumber: 1, trackLength: convertToSeconds(from: "03:32"), features: nil),
       SongModel(songTitle: "Blank Space", album: .eightyNine, trackNumber: 2, trackLength: convertToSeconds(from: "03:51"), features: nil),
       SongModel(songTitle: "Style", album: .eightyNine, trackNumber: 3, trackLength: convertToSeconds(from: "03:51"), features: nil),
       SongModel(songTitle: "Out of the Woods", album: .eightyNine, trackNumber: 4, trackLength: convertToSeconds(from: "03:55"), features: nil),
       SongModel(songTitle: "All You Had To Do Was Stay", album: .eightyNine, trackNumber: 5, trackLength: convertToSeconds(from: "03:13"), features: nil),
       SongModel(songTitle: "Shake It Off", album: .eightyNine, trackNumber: 6, trackLength: convertToSeconds(from: "03:39"), features: nil),
       SongModel(songTitle: "I Wish You Would", album: .eightyNine, trackNumber: 7, trackLength: convertToSeconds(from: "03:27"), features: nil),
       SongModel(songTitle: "Bad Blood", album: .eightyNine, trackNumber: 8, trackLength: convertToSeconds(from: "03:31"), features: nil),
       SongModel(songTitle: "Wildest Dreams", album: .eightyNine, trackNumber: 9, trackLength: convertToSeconds(from: "03:40"), features: nil),
       SongModel(songTitle: "How You Get The Girl", album: .eightyNine, trackNumber: 10, trackLength: convertToSeconds(from: "04:07"), features: nil),
       SongModel(songTitle: "This Love", album: .eightyNine, trackNumber: 11, trackLength: convertToSeconds(from: "04:10"), features: nil),
       SongModel(songTitle: "I Know Places", album: .eightyNine, trackNumber: 12, trackLength: convertToSeconds(from: "03:15"), features: nil),
       SongModel(songTitle: "Clean", album:.eightyNine, trackNumber: 13, trackLength: convertToSeconds(from: "04:31"), features: nil),
       SongModel(songTitle: "Wonderland", album: .eightyNine, trackNumber: 14, trackLength: convertToSeconds(from: "04:05"), features: nil),
       SongModel(songTitle: "You Are In Love", album: .eightyNine, trackNumber: 15, trackLength: convertToSeconds(from: "04:27"), features: nil),
       SongModel(songTitle: "New Romantics", album: .eightyNine, trackNumber: 16, trackLength: convertToSeconds(from: "03:50"), features: nil),
    SongModel(songTitle: "Slut!", album: .eightyNine, trackNumber: 17, trackLength: convertToSeconds(from: "03:00"), features: nil),
       SongModel(songTitle: "Say Don't Go", album: .eightyNine, trackNumber: 18, trackLength: convertToSeconds(from: "04:39"), features: nil),
       SongModel(songTitle: "Now That We Don't Talk", album: .eightyNine, trackNumber: 19, trackLength: convertToSeconds(from: "02:26"), features: nil),
       SongModel(songTitle: "Suburban Legends", album: .eightyNine, trackNumber: 20, trackLength: convertToSeconds(from: "02:51"), features: nil),
       SongModel(songTitle: "Is It Over Now?", album: .eightyNine, trackNumber: 21, trackLength: convertToSeconds(from: "03:49"), features: nil),
       SongModel(songTitle: "Sweeter than Fiction", album: .eightyNine, trackNumber: 22, trackLength: convertToSeconds(from: "03:54"), features: nil),
       SongModel(songTitle: "Bad Blood feat. Kendrick Lamar", album: .eightyNine, trackNumber: 23, trackLength: convertToSeconds(from: "03:20"), features: "Kendrick Lamar"),
    //RED
    SongModel(songTitle: "State of Grace", album: .Red, trackNumber: 1, trackLength: convertToSeconds(from: "04:55"), features: nil),
      SongModel(songTitle: "Red", album: .Red, trackNumber: 2, trackLength: convertToSeconds(from: "03:43"), features: nil),
      SongModel(songTitle: "Treacherous", album: .Red, trackNumber: 3, trackLength: convertToSeconds(from: "04:02"), features: nil),
      SongModel(songTitle: "I Knew You Were Trouble", album: .Red, trackNumber: 4, trackLength: convertToSeconds(from: "03:39"), features: nil),
      SongModel(songTitle: "All Too Well", album: .Red, trackNumber: 5, trackLength: convertToSeconds(from: "05:29"), features: nil),
      SongModel(songTitle: "22", album: .Red, trackNumber: 6, trackLength: convertToSeconds(from: "03:50"), features: nil),
      SongModel(songTitle: "I Almost Do", album: .Red, trackNumber: 7, trackLength: convertToSeconds(from: "04:04"), features: nil),
      SongModel(songTitle: "We Are Never Ever Getting Back Together", album: .Red, trackNumber: 8, trackLength: convertToSeconds(from: "03:13"), features: nil),
      SongModel(songTitle: "Stay Stay Stay", album: .Red, trackNumber: 9, trackLength: convertToSeconds(from: "03:25"), features: nil),
      SongModel(songTitle: "The Last Time", album: .Red, trackNumber: 10, trackLength: convertToSeconds(from: "04:59"), features: "Gary Lightbody of Snow Patrol"),
      SongModel(songTitle: "Holy Ground", album: .Red, trackNumber: 11, trackLength: convertToSeconds(from: "03:22"), features: nil),
      SongModel(songTitle: "Sad Beautiful Tragic", album: .Red, trackNumber: 12, trackLength: convertToSeconds(from: "04:44"), features: nil),
      SongModel(songTitle: "The Lucky One", album: .Red, trackNumber: 13, trackLength: convertToSeconds(from: "04:00"), features: nil),
      SongModel(songTitle: "Everything Has Changed", album: .Red, trackNumber: 14, trackLength: convertToSeconds(from: "04:05"), features: "Ed Sheeran"),
      SongModel(songTitle: "Starlight", album: .Red, trackNumber: 15, trackLength: convertToSeconds(from: "03:40"), features: nil),
      SongModel(songTitle: "Begin Again", album: .Red, trackNumber: 16, trackLength: convertToSeconds(from: "03:58"), features: nil),
      SongModel(songTitle: "The Moment I Knew", album: .Red, trackNumber: 17, trackLength: convertToSeconds(from: "04:45"), features: nil),
      SongModel(songTitle: "Come Back... Be Here", album: .Red, trackNumber: 18, trackLength: convertToSeconds(from: "03:43"), features: nil),
      SongModel(songTitle: "Girl at Home", album: .Red, trackNumber: 19, trackLength: convertToSeconds(from: "03:40"), features: nil),
      SongModel(songTitle: "State of Grace (acoustic version)", album: .Red, trackNumber: 20, trackLength: convertToSeconds(from: "05:21"), features: nil),
      SongModel(songTitle: "Ronan", album: .Red, trackNumber: 21, trackLength: convertToSeconds(from: "04:24"), features: nil),
      SongModel(songTitle: "Better Man", album: .Red, trackNumber: 22, trackLength: convertToSeconds(from: "04:57"), features: nil),
      SongModel(songTitle: "Nothing New", album: .Red, trackNumber: 23, trackLength: convertToSeconds(from: "04:18"), features: "Phoebe Bridgers"),
      SongModel(songTitle: "Babe", album: .Red, trackNumber: 24, trackLength: convertToSeconds(from: "03:44"), features: nil),
      SongModel(songTitle: "Message In A Bottle", album: .Red, trackNumber: 25, trackLength: convertToSeconds(from: "03:45"), features: nil),
      SongModel(songTitle: "I Bet You Think About Me", album: .Red, trackNumber: 26, trackLength: convertToSeconds(from: "04:45"), features: "Chris Stapleton"),
      SongModel(songTitle: "Forever Winter", album: .Red, trackNumber: 27, trackLength: convertToSeconds(from: "04:23"), features: nil),
      SongModel(songTitle: "Run", album: .Red, trackNumber: 28, trackLength: convertToSeconds(from: "04:00"), features: "Ed Sheeran"),
      SongModel(songTitle: "The Very First Night", album: .Red, trackNumber: 29, trackLength: convertToSeconds(from: "03:20"), features: nil),
      SongModel(songTitle: "All Too Well (10 Minute Version)", album: .Red, trackNumber: 30, trackLength: convertToSeconds(from: "10:13"), features: nil)



]

